<?php

namespace App\Imports;

use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithValidation;
use Maatwebsite\Excel\Concerns\Importable;
use App\Models\DosenTetap;

class DosenTetapImport implements ToModel, WithValidation
{
    use Importable;

    public function model(array $row)
    {
        return new DosenTetap([
            'email' => $row[0],
            'bulan' => $row[1],
            'tahun' => $row[2],
            'nama' => $row[3],
            'jabatan_struktural' => $row[4],
            'jabatan_fungsional' => $row[5],
            'gaji_pokok' => $row[6],
            'tunjangan_kehadiran' => $row[7],
            'tunjangan_jabatan_struktural' => $row[8],
            'tunjangan_jabatan_fungsional' => $row[9],
            'honor_mengajar_kls_pagi' => $row[10],
            'x_honor_mengajar_kls_pagi' => $row[11],
            'nominal_honor_mengajar_kls_pagi' => $row[12],
            'honor_mengajar_kls_malam' => $row[13],
            'x_honor_mengajar_kls_malam' => $row[14],
            'nominal_honor_mengajar_kls_malam' => $row[15],
            'pmb_atau_penguji_kp' => $row[16],
            'x_pmb_atau_penguji_kp' => $row[17],
            'nominal_pmb_atau_penguji_kp' => $row[18],
            'pmb_1_proposal_pagi' => $row[19],
            'x_pmb_1_proposal_pagi' => $row[20],
            'nominal_pmb_1_proposal_pagi' => $row[21],
            'pmb_1_proposal_malam' => $row[22],
            'x_pmb_1_proposal_malam' => $row[23],
            'nominal_pmb_1_proposal_malam' => $row[24],
            'pmb_1_skripsi_pagi' => $row[25],
            'x_pmb_1_skripsi_pagi' => $row[26],
            'nominal_pmb_1_skripsi_pagi' => $row[27],
            'pmb_1_skripsi_malam' => $row[28],
            'x_pmb_1_skripsi_malam' => $row[29],
            'nominal_pmb_1_skripsi_malam' => $row[30],
            'pmb_2_proposal_pagi' => $row[31],
            'x_pmb_2_proposal_pagi' => $row[32],
            'nominal_pmb_2_proposal_pagi' => $row[33],
            'pmb_2_proposal_malam' => $row[34],
            'x_pmb_2_proposal_malam' => $row[35],
            'nominal_pmb_2_proposal_malam' => $row[36],
            'pmb_2_skripsi_pagi' => $row[37],
            'x_pmb_2_skripsi_pagi' => $row[38],
            'nominal_pmb_2_skripsi_pagi' => $row[39],
            'pmb_2_skripsi_malam' => $row[40],
            'x_pmb_2_skripsi_malam' => $row[41],
            'nominal_pmb_2_skripsi_malam' => $row[42],
            'penguji_sidang_proposal' => $row[43],
            'x_penguji_sidang_proposal' => $row[44],
            'nominal_penguji_sidang_proposal' => $row[45],
            'penguji_sidang_skripsi' => $row[46],
            'x_penguji_sidang_skripsi' => $row[47],
            'nominal_penguji_sidang_skripsi' => $row[48],
            'koreksi_soal' => $row[49],
            'x_koreksi_soal' => $row[50],
            'nominal_koreksi_soal' => $row[51],
            'pembuatan_soal' => $row[52],
            'x_pembuatan_soal' => $row[53],
            'nominal_pembuatan_soal' => $row[54],
            'dosen_wali' => $row[55],
            'x_dosen_wali' => $row[56],
            'nominal_dosen_wali' => $row[57],
            'pengawas_ujian' => $row[58],
            'x_pengawas_ujian' => $row[59],
            'nominal_pengawas_ujian' => $row[60],
            'remidial' => $row[61],
            'x_remidial' => $row[62],
            'nominal_remidial' => $row[63],
            'pmb_company_visit' => $row[64],
            'x_pmb_company_visit' => $row[65],
            'nominal_pmb_company_visit' => $row[66],
            'pembina_ukm' => $row[67],
            'reward_ekin' => $row[68],
            'jumlah_gaji_tunjangan_honor' => $row[69],
            'potongan_kas_bon' => $row[70],
            'pph_21' => $row[71],
            'potongan_absensi' => $row[72],
            'potongan_bpjs' => $row[73],
            'jumlah' => $row[74],
            'gaji_yang_dibayar' => $row[75]
        ]);
    }

    public function rules(): array
    {
        return [
            '0' => 'required|string|max:100',
            '1' => 'required|integer',
            '2' => 'required|integer',
            '3' => 'required|string|max:100',
            '4' => 'required|string|max:100',
            '5' => 'required|string|max:100',
            '6' => 'required|integer',
            '7' => 'required|integer',
            '8' => 'required|integer',
            '9' => 'required|integer',
            '10' => 'required|integer',
            '11' => 'required|integer',
            '12' => 'required|integer',
            '13' => 'required|integer',
            '14' => 'required|integer',
            '15' => 'required|integer',
            '16' => 'required|integer',
            '17' => 'required|integer',
            '18' => 'required|integer',
            '19' => 'required|integer',
            '20' => 'required|integer',
            '21' => 'required|integer',
            '22' => 'required|integer',
            '23' => 'required|integer',
            '24' => 'required|integer',
            '25' => 'required|integer',
            '26' => 'required|integer',
            '27' => 'required|integer',
            '28' => 'required|integer',
            '29' => 'required|integer',
            '30' => 'required|integer',
            '31' => 'required|integer',
            '32' => 'required|integer',
            '33' => 'required|integer',
            '34' => 'required|integer',
            '35' => 'required|integer',
            '36' => 'required|integer',
            '37' => 'required|integer',
            '38' => 'required|integer',
            '39' => 'required|integer',
            '40' => 'required|integer',
            '41' => 'required|integer',
            '42' => 'required|integer',
            '43' => 'required|integer',
            '44' => 'required|integer',
            '45' => 'required|integer',
            '46' => 'required|integer',
            '47' => 'required|integer',
            '48' => 'required|integer',
            '49' => 'required|integer',
            '50' => 'required|integer',
            '51' => 'required|integer',
            '52' => 'required|integer',
            '53' => 'required|integer',
            '54' => 'required|integer',
            '55' => 'required|integer',
            '56' => 'required|integer',
            '57' => 'required|integer',
            '58' => 'required|integer',
            '59' => 'required|integer',
            '60' => 'required|integer',
            '61' => 'required|integer',
            '62' => 'required|integer',
            '63' => 'required|integer',
            '64' => 'required|integer',
            '65' => 'required|integer',
            '66' => 'required|integer',
            '67' => 'required|integer',
            '68' => 'required|integer',
            '69' => 'required|integer',
            '70' => 'required|integer',
            '71' => 'required|integer',
            '72' => 'required|integer',
            '73' => 'required|integer',
            '74' => 'required|integer',
            '75' => 'required|integer'
        ];
    }
}
