<?php

namespace App\Imports;

use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow; // row 1 sebagai heading
use Maatwebsite\Excel\Concerns\WithValidation; // validasi string / integer
use Maatwebsite\Excel\Concerns\Importable;
use App\Models\DosenTetap;

class DosenTetapImport implements ToModel, WithHeadingRow, WithValidation // Gunakan WithHeadingRow
{
    use Importable;

    public function model(array $row)
    {
        return new DosenTetap([
            'email' => $row['email'],
            'bulan' => $row['bulan'],
            'tahun' => $row['tahun'],
            'nama' => $row['nama'],
            'jabatan_struktural' => $row['jabatan_struktural'],
            'jabatan_fungsional' => $row['jabatan_fungsional'],
            'gaji_pokok' => $row['gaji_pokok'],
            'tunjangan_kehadiran' => $row['tunjangan_kehadiran'],
            'tunjangan_jabatan_struktural' => $row['tunjangan_jabatan_struktural'],
            'tunjangan_jabatan_fungsional' => $row['tunjangan_jabatan_fungsional'],
            'honor_mengajar_kls_pagi' => $row['honor_mengajar_kls_pagi'],
            'x_honor_mengajar_kls_pagi' => $row['x_honor_mengajar_kls_pagi'],
            'nominal_honor_mengajar_kls_pagi' => $row['nominal_honor_mengajar_kls_pagi'],
            'honor_mengajar_kls_malam' => $row['honor_mengajar_kls_malam'],
            'x_honor_mengajar_kls_malam' => $row['x_honor_mengajar_kls_malam'],
            'nominal_honor_mengajar_kls_malam' => $row['nominal_honor_mengajar_kls_malam'],
            'pmb_atau_penguji_kp' => $row['pmb_atau_penguji_kp'],
            'x_pmb_atau_penguji_kp' => $row['x_pmb_atau_penguji_kp'],
            'nominal_pmb_atau_penguji_kp' => $row['nominal_pmb_atau_penguji_kp'],
            'pmb_1_proposal_pagi' => $row['pmb_1_proposal_pagi'],
            'x_pmb_1_proposal_pagi' => $row['x_pmb_1_proposal_pagi'],
            'nominal_pmb_1_proposal_pagi' => $row['nominal_pmb_1_proposal_pagi'],
            'pmb_1_proposal_malam' => $row['pmb_1_proposal_malam'],
            'x_pmb_1_proposal_malam' => $row['x_pmb_1_proposal_malam'],
            'nominal_pmb_1_proposal_malam' => $row['nominal_pmb_1_proposal_malam'],
            'pmb_1_skripsi_pagi' => $row['pmb_1_skripsi_pagi'],
            'x_pmb_1_skripsi_pagi' => $row['x_pmb_1_skripsi_pagi'],
            'nominal_pmb_1_skripsi_pagi' => $row['nominal_pmb_1_skripsi_pagi'],
            'pmb_1_skripsi_malam' => $row['pmb_1_skripsi_malam'],
            'x_pmb_1_skripsi_malam' => $row['x_pmb_1_skripsi_malam'],
            'nominal_pmb_1_skripsi_malam' => $row['nominal_pmb_1_skripsi_malam'],
            'pmb_2_proposal_pagi' => $row['pmb_2_proposal_pagi'],
            'x_pmb_2_proposal_pagi' => $row['x_pmb_2_proposal_pagi'],
            'nominal_pmb_2_proposal_pagi' => $row['nominal_pmb_2_proposal_pagi'],
            'pmb_2_proposal_malam' => $row['pmb_2_proposal_malam'],
            'x_pmb_2_proposal_malam' => $row['x_pmb_2_proposal_malam'],
            'nominal_pmb_2_proposal_malam' => $row['nominal_pmb_2_proposal_malam'],
            'pmb_2_skripsi_pagi' => $row['pmb_2_skripsi_pagi'],
            'x_pmb_2_skripsi_pagi' => $row['x_pmb_2_skripsi_pagi'],
            'nominal_pmb_2_skripsi_pagi' => $row['nominal_pmb_2_skripsi_pagi'],
            'pmb_2_skripsi_malam' => $row['pmb_2_skripsi_malam'],
            'x_pmb_2_skripsi_malam' => $row['x_pmb_2_skripsi_malam'],
            'nominal_pmb_2_skripsi_malam' => $row['nominal_pmb_2_skripsi_malam'],
            'penguji_sidang_proposal' => $row['penguji_sidang_proposal'],
            'x_penguji_sidang_proposal' => $row['x_penguji_sidang_proposal'],
            'nominal_penguji_sidang_proposal' => $row['nominal_penguji_sidang_proposal'],
            'penguji_sidang_skripsi' => $row['penguji_sidang_skripsi'],
            'x_penguji_sidang_skripsi' => $row['x_penguji_sidang_skripsi'],
            'nominal_penguji_sidang_skripsi' => $row['nominal_penguji_sidang_skripsi'],
            'koreksi_soal' => $row['koreksi_soal'],
            'x_koreksi_soal' => $row['x_koreksi_soal'],
            'nominal_koreksi_soal' => $row['nominal_koreksi_soal'],
            'pembuatan_soal' => $row['pembuatan_soal'],
            'x_pembuatan_soal' => $row['x_pembuatan_soal'],
            'nominal_pembuatan_soal' => $row['nominal_pembuatan_soal'],
            'dosen_wali' => $row['dosen_wali'],
            'x_dosen_wali' => $row['x_dosen_wali'],
            'nominal_dosen_wali' => $row['nominal_dosen_wali'],
            'pengawas_ujian' => $row['pengawas_ujian'],
            'x_pengawas_ujian' => $row['x_pengawas_ujian'],
            'nominal_pengawas_ujian' => $row['nominal_pengawas_ujian'],
            'remidial' => $row['remidial'],
            'x_remidial' => $row['x_remidial'],
            'nominal_remidial' => $row['nominal_remidial'],
            'pmb_company_visit' => $row['pmb_company_visit'],
            'x_pmb_company_visit' => $row['x_pmb_company_visit'],
            'nominal_pmb_company_visit' => $row['nominal_pmb_company_visit'],
            'pembina_ukm' => $row['pembina_ukm'],
            'reward_ekin' => $row['reward_ekin'],
            'jumlah_gaji_tunjangan_honor' => $row['jumlah_gaji_tunjangan_honor'],
            'potongan_kas_bon' => $row['potongan_kas_bon'],
            'pph_21' => $row['pph_21'],
            'potongan_absensi' => $row['potongan_absensi'],
            'potongan_bpjs' => $row['potongan_bpjs'],
            'jumlah' => $row['jumlah'],
            'gaji_yang_dibayar' => $row['gaji_yang_dibayar']            
        ]);
    }

    public function rules(): array
    {
        return [
            'email' => 'required|string|max:100',
            'bulan' => 'required|integer',
            'tahun' => 'required|integer',
            'nama' => 'required|string|max:100',
            'jabatan_struktural' => 'required|string|max:100',
            'jabatan_fungsional' => 'required|string|max:100',
            'gaji_pokok' => 'required|integer',
            'tunjangan_kehadiran' => 'required|integer',
            'tunjangan_jabatan_struktural' => 'required|integer',
            'tunjangan_jabatan_fungsional' => 'required|integer',
            'honor_mengajar_kls_pagi' => 'required|integer',
            'x_honor_mengajar_kls_pagi' => 'required|integer',
            'nominal_honor_mengajar_kls_pagi' => 'required|integer',
            'honor_mengajar_kls_malam' => 'required|integer',
            'x_honor_mengajar_kls_malam' => 'required|integer',
            'nominal_honor_mengajar_kls_malam' => 'required|integer',
            'pmb_atau_penguji_kp' => 'required|integer',
            'x_pmb_atau_penguji_kp' => 'required|integer',
            'nominal_pmb_atau_penguji_kp' => 'required|integer',
            'pmb_1_proposal_pagi' => 'required|integer',
            'x_pmb_1_proposal_pagi' => 'required|integer',
            'nominal_pmb_1_proposal_pagi' => 'required|integer',
            'pmb_1_proposal_malam' => 'required|integer',
            'x_pmb_1_proposal_malam' => 'required|integer',
            'nominal_pmb_1_proposal_malam' => 'required|integer',
            'pmb_1_skripsi_pagi' => 'required|integer',
            'x_pmb_1_skripsi_pagi' => 'required|integer',
            'nominal_pmb_1_skripsi_pagi' => 'required|integer',
            'pmb_1_skripsi_malam' => 'required|integer',
            'x_pmb_1_skripsi_malam' => 'required|integer',
            'nominal_pmb_1_skripsi_malam' => 'required|integer',
            'pmb_2_proposal_pagi' => 'required|integer',
            'x_pmb_2_proposal_pagi' => 'required|integer',
            'nominal_pmb_2_proposal_pagi' => 'required|integer',
            'pmb_2_proposal_malam' => 'required|integer',
            'x_pmb_2_proposal_malam' => 'required|integer',
            'nominal_pmb_2_proposal_malam' => 'required|integer',
            'pmb_2_skripsi_pagi' => 'required|integer',
            'x_pmb_2_skripsi_pagi' => 'required|integer',
            'nominal_pmb_2_skripsi_pagi' => 'required|integer',
            'pmb_2_skripsi_malam' => 'required|integer',
            'x_pmb_2_skripsi_malam' => 'required|integer',
            'nominal_pmb_2_skripsi_malam' => 'required|integer',
            'penguji_sidang_proposal' => 'required|integer',
            'x_penguji_sidang_proposal' => 'required|integer',
            'nominal_penguji_sidang_proposal' => 'required|integer',
            'penguji_sidang_skripsi' => 'required|integer',
            'x_penguji_sidang_skripsi' => 'required|integer',
            'nominal_penguji_sidang_skripsi' => 'required|integer',
            'koreksi_soal' => 'required|integer',
            'x_koreksi_soal' => 'required|integer',
            'nominal_koreksi_soal' => 'required|integer',
            'pembuatan_soal' => 'required|integer',
            'x_pembuatan_soal' => 'required|integer',
            'nominal_pembuatan_soal' => 'required|integer',
            'dosen_wali' => 'required|integer',
            'x_dosen_wali' => 'required|integer',
            'nominal_dosen_wali' => 'required|integer',
            'pengawas_ujian' => 'required|integer',
            'x_pengawas_ujian' => 'required|integer',
            'nominal_pengawas_ujian' => 'required|integer',
            'remidial' => 'required|integer',
            'x_remidial' => 'required|integer',
            'nominal_remidial' => 'required|integer',
            'pmb_company_visit' => 'required|integer',
            'x_pmb_company_visit' => 'required|integer',
            'nominal_pmb_company_visit' => 'required|integer',
            'pembina_ukm' => 'required|integer',
            'reward_ekin' => 'required|integer',
            'jumlah_gaji_tunjangan_honor' => 'required|integer',
            'potongan_kas_bon' => 'required|integer',
            'pph_21' => 'required|integer',
            'potongan_absensi' => 'required|integer',
            'potongan_bpjs' => 'required|integer',
            'jumlah' => 'required|integer',
            'gaji_yang_dibayar' => 'required|integer'
            
        ];
    }
}
